### ISSUE TITLE
Exception while parsing fig files

### ISSUE THREAD

**Issue by tpalsulich** [diffplug/JMatIO#2]
Are figures supported? I am getting the following exception when trying to parse .fig files with JMatIO through Apache Tika:
```
Exception in thread "main" org.apache.tika.exception.TikaException: Error parsing Matlab file with MatParser
	at org.apache.tika.parser.mat.MatParser.parse(MatParser.java:128)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:256)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:256)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
	at org.apache.tika.cli.TikaCLI$OutputType.process(TikaCLI.java:146)
	at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:440)
	at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:116)
Caused by: com.jmatio.io.MatlabIOException: Incorrect matlab array class: function_handle
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:929)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:639)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:620)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:620)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:620)
	at com.jmatio.io.MatFileReader.readMatrix(MatFileReader.java:620)
	at com.jmatio.io.MatFileReader.readData(MatFileReader.java:515)
	at com.jmatio.io.MatFileReader.readData(MatFileReader.java:498)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:298)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:154)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:130)
	at org.apache.tika.parser.mat.MatParser.parse(MatParser.java:66)
	... 6 more
```

The line in master that's throwing the exception is https://github.com/codemercenary/JMatIO/blob/master/src/main/java/ca/mjdsystems/jmatio/io/MatFileReader.java#L1287. You can grab a sample fig file from [this](http://www.mathworks.cn/matlabcentral/fileexchange/downloads/7534) zip file. [Here](https://issues.apache.org/jira/browse/TIKA-1458) is the relevant Tika JIRA issue.

**Comment by nedtwigg** [comment]
This is probably because JMatIO doesn't support unsigned 16-bit integers.  This feature has been added to [MatFileRW](https://github.com/diffplug/matfilerw#codemercenaryjmatio-and-camjdsystemsjmatio), an actively maintained fork with a direct migration path.  I think you'll find that this will fix the issue.  If it doesn't, feel free to reopen an issue there and I'll address it ASAP.
